// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgvngm6JYzv_eb6GkH9ddwgLbRhqXmSD0',
    appId: '1:541119050371:web:464fca769d9305c40de1b6',
    messagingSenderId: '541119050371',
    projectId: 'pet-care-app-8c99f',
    authDomain: 'pet-care-app-8c99f.firebaseapp.com',
    storageBucket: 'pet-care-app-8c99f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiU2M66VFn4hoKpSoWSk-lP8Nsn0ZBOeo',
    appId: '1:541119050371:android:13309bedd55c7e3a0de1b6',
    messagingSenderId: '541119050371',
    projectId: 'pet-care-app-8c99f',
    storageBucket: 'pet-care-app-8c99f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFoZlFQvH1z5eTjEOASMIRO8kfh6VWhcI',
    appId: '1:541119050371:ios:3b2de60c8d8e1ff50de1b6',
    messagingSenderId: '541119050371',
    projectId: 'pet-care-app-8c99f',
    storageBucket: 'pet-care-app-8c99f.firebasestorage.app',
    iosBundleId: 'com.example.misProekt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFoZlFQvH1z5eTjEOASMIRO8kfh6VWhcI',
    appId: '1:541119050371:ios:3b2de60c8d8e1ff50de1b6',
    messagingSenderId: '541119050371',
    projectId: 'pet-care-app-8c99f',
    storageBucket: 'pet-care-app-8c99f.firebasestorage.app',
    iosBundleId: 'com.example.misProekt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgvngm6JYzv_eb6GkH9ddwgLbRhqXmSD0',
    appId: '1:541119050371:web:855d186e86be9ad90de1b6',
    messagingSenderId: '541119050371',
    projectId: 'pet-care-app-8c99f',
    authDomain: 'pet-care-app-8c99f.firebaseapp.com',
    storageBucket: 'pet-care-app-8c99f.firebasestorage.app',
  );
}
